# Generated by Django 3.0.8 on 2021-03-13 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0002_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='transaction',
            name='direction',
            field=models.CharField(choices=[('INCOMING', 'incoming'), ('OUTGOING', 'outgoing')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tag',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('transac_type', models.CharField(choices=[('DEBIT', 'debit'), ('CREDIT', 'credit')], max_length=20)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.Transaction')),
                ('wallet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v0.Wallet')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v0.Wallet'),
        ),
    ]
