# Generated by Django 3.0.8 on 2021-03-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0003_auto_20210313_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='user',
            new_name='tag',
        ),
    ]
