# Generated by Django 3.0.8 on 2021-03-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0004_auto_20210313_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='tag',
            new_name='user_id',
        ),
    ]
