# Generated by Django 3.0.8 on 2021-03-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0007_auto_20210313_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='wallet_id',
            new_name='wallet',
        ),
        migrations.RenameField(
            model_name='transactionevent',
            old_name='transaction_id',
            new_name='transaction',
        ),
    ]
