# Generated by Django 3.0.8 on 2021-03-18 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0009_transaction_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionevent',
            old_name='transac_type',
            new_name='transaction_type',
        ),
    ]
