# Generated by Django 3.0.8 on 2021-03-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0011_auto_20210319_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionevent',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
